### ISSUE TITLE
installation issue on mac

### ISSUE THREAD

**Issue by naveen12** [sensepost/objection#38]
hi 
by fallowing the installation steps in mac
- virtual' installation completed and while doing "pip3 install -U objection" it showing issue as in error 
so have downloaded the git "git clone https://github.com/sensepost/objection.git"
then ran "pip install -r requirements.txt --user" 
then am confused how to open the objection module 
$objection explore
-bash: objection: command not found

am confused when am i missed

when i directly runs the "pip3 install -U objection"  it showing below error
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-build-eubc01_f/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-ug5xpgoh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-build-eubc01_f/frida/

please help me

python default is 2.7
newly installed is 3.6
by using the virtual installation used "pip3 install -U objection"
virtual-python3) ymac:objection apple$ pip3 install -U objection
Collecting objection
Collecting frida (from objection)
Using cached frida-10.6.21.tar.gz
Collecting jsbeautifier (from objection)
Collecting requests (from objection)
Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting tabulate (from objection)
Requirement already up-to-date: prompt-toolkit in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Requirement already up-to-date: delegator.py in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Collecting click (from objection)
Using cached click-6.7-py2.py3-none-any.whl
Collecting jinja2 (from objection)
Using cached Jinja2-2.10-py2.py3-none-any.whl
Requirement already up-to-date: colorama>=0.2.7 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from frida->objection)
Requirement already up-to-date: pygments>=2.0.2 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from frida->objection)
Collecting editorconfig>=0.12.0 (from jsbeautifier->objection)
Using cached EditorConfig-0.12.1-py3-none-any.whl
Requirement already up-to-date: six>=1.6.1 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from jsbeautifier->objection)
Collecting idna<2.7,>=2.5 (from requests->objection)
Using cached idna-2.6-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->objection)
Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->objection)
Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->objection)
Using cached urllib3-1.22-py2.py3-none-any.whl
Requirement already up-to-date: wcwidth in /Users/apple/virtual-python3/lib/python3.6/site-packages (from prompt-toolkit->objection)
Requirement already up-to-date: pexpect>=4.1.0 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from delegator.py->objection)
Collecting MarkupSafe>=0.23 (from jinja2->objection)
Requirement already up-to-date: ptyprocess>=0.5 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from pexpect>=4.1.0->delegator.py->objection)
Building wheels for collected packages: frida
Running setup.py bdist_wheel for frida ... error
Complete output from command /Users/apple/virtual-python3/bin/python3 -u -c "import setuptools, tokenize;file='/private/var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-build-t_8qf4qi/frida/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" bdist_wheel -d /var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/tmpmdvqjc5hpip-wheel- --python-tag cp36:
running bdist_wheel
running build
running build_py
creating build
creating build/lib.macosx-10.6-intel-3.6
creating build/lib.macosx-10.6-intel-3.6/frida
copying frida/init.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/application.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/core.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/discoverer.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/kill.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/lsd.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/ps.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/repl.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/tracer.py -> build/lib.macosx-10.6-intel-3.6/frida
running build_ext
querying pypi for available prebuilds
network query failed
looking for prebuilt extension in home directory, i.e. /Users/apple/frida-10.6.21-py3.6-macosx-10.6-intel.egg
no prebuilt extension found in home directory
error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

Failed building wheel for frida
Running setup.py clean for frida
Failed to build frida
Installing collected packages: frida, editorconfig, jsbeautifier, idna, certifi, chardet, urllib3, requests, tabulate, click, MarkupSafe, jinja2, objection
Running setup.py install for frida ... error
Complete output from command /Users/apple/virtual-python3/bin/python3 -u -c "import setuptools, tokenize;file='/private/var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-build-t_8qf4qi/frida/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-e8dmrzjl-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/apple/virtual-python3/bin/../include/site/python3.6/frida:
running install
running build
running build_py
creating build
creating build/lib.macosx-10.6-intel-3.6
creating build/lib.macosx-10.6-intel-3.6/frida
copying frida/init.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/application.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/core.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/discoverer.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/kill.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/lsd.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/ps.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/repl.py -> build/lib.macosx-10.6-intel-3.6/frida
copying frida/tracer.py -> build/lib.macosx-10.6-intel-3.6/frida
running build_ext
querying pypi for available prebuilds
network query failed
looking for prebuilt extension in home directory, i.e. /Users/apple/frida-10.6.21-py3.6-macosx-10.6-intel.egg
no prebuilt extension found in home directory
error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

----------------------------------------
Command "/Users/apple/virtual-python3/bin/python3 -u -c "import setuptools, tokenize;file='/private/var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-build-t_8qf4qi/frida/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-e8dmrzjl-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/apple/virtual-python3/bin/../include/site/python3.6/frida" failed with error code 1 in /private/var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-build-t_8qf4qi/frida/
(virtual-python3) ymac:objection apple$

**Comment by naveen12** [comment]
python default is 2.7
newly installed is 3.6 
by using the virtual installation used "pip3 install -U objection"
virtual-python3) ymac:objection apple$ pip3 install -U objection
Collecting objection
Collecting frida (from objection)
  Using cached frida-10.6.21.tar.gz
Collecting jsbeautifier (from objection)
Collecting requests (from objection)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting tabulate (from objection)
Requirement already up-to-date: prompt-toolkit in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Requirement already up-to-date: delegator.py in /Users/apple/virtual-python3/lib/python3.6/site-packages (from objection)
Collecting click (from objection)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting jinja2 (from objection)
  Using cached Jinja2-2.10-py2.py3-none-any.whl
Requirement already up-to-date: colorama>=0.2.7 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from frida->objection)
Requirement already up-to-date: pygments>=2.0.2 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from frida->objection)
Collecting editorconfig>=0.12.0 (from jsbeautifier->objection)
  Using cached EditorConfig-0.12.1-py3-none-any.whl
Requirement already up-to-date: six>=1.6.1 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from jsbeautifier->objection)
Collecting idna<2.7,>=2.5 (from requests->objection)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->objection)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->objection)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->objection)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Requirement already up-to-date: wcwidth in /Users/apple/virtual-python3/lib/python3.6/site-packages (from prompt-toolkit->objection)
Requirement already up-to-date: pexpect>=4.1.0 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from delegator.py->objection)
Collecting MarkupSafe>=0.23 (from jinja2->objection)
Requirement already up-to-date: ptyprocess>=0.5 in /Users/apple/virtual-python3/lib/python3.6/site-packages (from pexpect>=4.1.0->delegator.py->objection)
Building wheels for collected packages: frida
  Running setup.py bdist_wheel for frida ... error
  Complete output from command /Users/apple/virtual-python3/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-build-t_8qf4qi/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/tmpmdvqjc5hpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-3.6
  creating build/lib.macosx-10.6-intel-3.6/frida
  copying frida/__init__.py -> build/lib.macosx-10.6-intel-3.6/frida
  copying frida/application.py -> build/lib.macosx-10.6-intel-3.6/frida
  copying frida/core.py -> build/lib.macosx-10.6-intel-3.6/frida
  copying frida/discoverer.py -> build/lib.macosx-10.6-intel-3.6/frida
  copying frida/kill.py -> build/lib.macosx-10.6-intel-3.6/frida
  copying frida/lsd.py -> build/lib.macosx-10.6-intel-3.6/frida
  copying frida/ps.py -> build/lib.macosx-10.6-intel-3.6/frida
  copying frida/repl.py -> build/lib.macosx-10.6-intel-3.6/frida
  copying frida/tracer.py -> build/lib.macosx-10.6-intel-3.6/frida
  running build_ext
  querying pypi for available prebuilds
  network query failed
  looking for prebuilt extension in home directory, i.e. /Users/apple/frida-10.6.21-py3.6-macosx-10.6-intel.egg
  no prebuilt extension found in home directory
  error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>
  
  ----------------------------------------
  Failed building wheel for frida
  Running setup.py clean for frida
Failed to build frida
Installing collected packages: frida, editorconfig, jsbeautifier, idna, certifi, chardet, urllib3, requests, tabulate, click, MarkupSafe, jinja2, objection
  Running setup.py install for frida ... error
    Complete output from command /Users/apple/virtual-python3/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-build-t_8qf4qi/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-e8dmrzjl-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/apple/virtual-python3/bin/../include/site/python3.6/frida:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    creating build/lib.macosx-10.6-intel-3.6/frida
    copying frida/__init__.py -> build/lib.macosx-10.6-intel-3.6/frida
    copying frida/application.py -> build/lib.macosx-10.6-intel-3.6/frida
    copying frida/core.py -> build/lib.macosx-10.6-intel-3.6/frida
    copying frida/discoverer.py -> build/lib.macosx-10.6-intel-3.6/frida
    copying frida/kill.py -> build/lib.macosx-10.6-intel-3.6/frida
    copying frida/lsd.py -> build/lib.macosx-10.6-intel-3.6/frida
    copying frida/ps.py -> build/lib.macosx-10.6-intel-3.6/frida
    copying frida/repl.py -> build/lib.macosx-10.6-intel-3.6/frida
    copying frida/tracer.py -> build/lib.macosx-10.6-intel-3.6/frida
    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. /Users/apple/frida-10.6.21-py3.6-macosx-10.6-intel.egg
    no prebuilt extension found in home directory
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>
    
    ----------------------------------------
Command "/Users/apple/virtual-python3/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-build-t_8qf4qi/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-e8dmrzjl-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/apple/virtual-python3/bin/../include/site/python3.6/frida" failed with error code 1 in /private/var/folders/z8/vxvtd5yj0ls68c72cgyn3pr00000gn/T/pip-build-t_8qf4qi/frida/
(virtual-python3) ymac:objection apple$

**Comment by naveen12** [comment]
installation issue was solved 
i have manually downloaded "frida-10.6.21-py3.6-macosx-10.6-intel.egg"  from site:https://pypi.python.org/pypi/frida 
and ran the pip3 install -U objection

**Comment by leonjza** [comment]
Hey,

I know you have already closed this issue, but something worth noting is the `error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>` line in the output you have pasted. This was the part the installation tried to download and install the `frida` dependency for you, but failed because the remote certificate failed to validate. If possible, double check that you do not have any intercepting proxies or anything in the way that would present you with an invalid SSL certificate when downloading from HTTPS URL's.

**Comment by Thireus** [comment]
Same issue here. It looks like Frida's certificate is bad (assuming this is the website where the materials are fetched).

https://www.frida.re/

> Certificate - missing
> This site is missing a valid, trusted certificate (net::ERR_CERT_VALIDITY_TOO_LONG).

Downloading and placing frida-10.7.7-py3.6-macosx-10.6-intel.egg in ~/ from https://pypi.python.org/pypi/frida solved the issue.

**Comment by bugwrangler** [comment]
You could also use the following commands -  

cd “/Applications/Python 3.6/”
sudo “./Install Certificates.command”

**Comment by sentago** [comment]
i'm having the same issue but i still can't fix it, everytime i use pip3 install -U objection

i get the below error:

Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/9k/gkg8xzc56_g6xv16y2x61y740000gn/T/pip-build-m9w3q9wn/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/9k/gkg8xzc56_g6xv16y2x61y740000gn/T/pip-loo25vmc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/9k/gkg8xzc56_g6xv16y2x61y740000gn/T/pip-build-m9w3q9wn/frida/

could you please help with this
